### ISSUE TITLE
[BUG] Notification sound is not playing on Windows 11

### ISSUE THREAD

**Issue by zbysiek** [DanielGilbert/dgMicMute#9]
Notification sound is not playing on Windows 11 23H2
App Release is v1.2.1. Let me know if the app stores logs that i can send over, '-verbose' does not return anything.

@AngryJKirk

**Comment by DanielGilbert** [comment]
Thanks a lot for your input! I don't think I will have any capacity to work on this tool in the foreseeable future. With that being said - if it worked before, I don't know what broke it. You might be missing the [Media Feature Pack](https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a).

**However!**

If it never worked in the first place, it simply might be because the setup containing the changes by @AngryJKirk has been in draft for almost three years. I just pressed the button a few minutes ago and published v1.3.0. Note, though: Windows comes with a built-in muting option for quite some time now. So you may not need this tool any longer.

Feel free to reopen this issue if the problem hasn't been solved.
